--
CREATE TABLE DIM_CATEGORY (
	SPORT_ID varchar(8) NOT NULL,
	GENDER varchar(8) NOT NULL,
	ID varchar(20) NOT NULL,
	COUNTRY_ID varchar(2),
	ERA_INNINGS numeric,
	"NAME" varchar(50),
	PRIMARY KEY (SPORT_ID,GENDER,ID)
);

--
CREATE TABLE DIM_CLUB (
	ID varchar(8) NOT NULL,
	COUNTRY_ID varchar(2) NOT NULL,
	"NAME" varchar(255),
	ADDRESS varchar(255),
	POSTAL_CODE varchar(16),
	CITY varchar(50),
	PROVINCE varchar(50),
	COUNTRY varchar(50),
	EMAIL varchar(255),
	WEBPAGE varchar(255),
	BALLPARK_ID varchar(8),
	PRESIDENT varchar(50),
	SECRETARY varchar(50),
	TREASURER varchar(50),
	GOVERNANCE_PERSON varchar(50),
	CLUB_LATITUDE numeric,
	CLUB_LONGITUDE numeric,
	STADIUM_LATITUDE numeric,
	STADIUM_LONGITUDE numeric,
	PRIMARY KEY (ID,COUNTRY_ID)
);

CREATE TABLE DIM_CLUB_COUNTRY_BRIDGE (
	CLUB_ID varchar(20) NOT NULL,
	COUNTRY_ID varchar(2) NOT NULL,
	CREBY varchar(32) DEFAULT 'user
   ',
	CRE timestamp DEFAULT sysdate
   ,
	LUBY varchar(32),
	LU timestamp,
	PRIMARY KEY (CLUB_ID,COUNTRY_ID)
);

CREATE TABLE DIM_COMPETITION (
	COMPETITION_ID varchar(20) NOT NULL,
	COMPETITION varchar(255),
	CREBY varchar(32) DEFAULT 'user
   ',
	CRE timestamp DEFAULT sysdate
   ,
	LUBY varchar(32),
	LU timestamp,
	PRIMARY KEY (COMPETITION_ID)
);

CREATE TABLE DIM_COMPETITION_COUNTRY_BRIDGE (
	COMPETITION_ID varchar(20) NOT NULL,
	COUNTRY_ID varchar(2) NOT NULL,
	CREBY varchar(32) DEFAULT 'user
   ',
	CRE timestamp DEFAULT sysdate
   ,
	LUBY varchar(32),
	LU timestamp,
	PRIMARY KEY (COMPETITION_ID,COUNTRY_ID)
);

--
CREATE TABLE DIM_COUNTRY (
	COUNTRY_ID varchar(2) NOT NULL,
	COUNTRY_NAME varchar(100),
	FEDERATION_ID varchar(20),
	ADDRESS varchar(255),
	POSTAL_CODE varchar(16),
	CITY varchar(50),
	PROVINCE varchar(50),
	EMAIL varchar(255),
	WEBPAGE varchar(255),
	PRIMARY KEY (COUNTRY_ID)
);

--
CREATE TABLE DIM_PLAYER (
	ID varchar(16) NOT NULL,
	LAST_NAME varchar(255),
	FIRST_NAME varchar(255),
	"POSITION" varchar(32),
	BATS varchar(10),
	THROWS varchar(10),
	YOB numeric,
	UNIFORM_NUMBER varchar(3),
	LICENSE_NUMBER varchar(16),
	LICENSE_TYPE varchar(8) DEFAULT 'null
   ',
	PRIMARY KEY (ID)
);

--
CREATE TABLE DIM_SEASON (
	SEASON_YEAR numeric NOT NULL,
	PRIMARY KEY (SEASON_YEAR)
);

--
CREATE TABLE DIM_SEASON_GAMES (
	SPORT_ID varchar(8) NOT NULL,
	GENDER_ID varchar(8) NOT NULL,
	CATEGORY_ID varchar(20) NOT NULL,
	COUNTRY_ID varchar(2) NOT NULL,
	SEASON_YEAR numeric NOT NULL,
	NUMBER_OF_GAMES numeric,
	PA_COEFFICIENT numeric,
	INNINGS_PITCHED_PERCENT numeric,
	PRIMARY KEY (SPORT_ID,GENDER_ID,CATEGORY_ID,COUNTRY_ID,SEASON_YEAR)
);

--
CREATE TABLE DIM_SPORT (
	ID varchar(8) NOT NULL,
	GENDER varchar(8) NOT NULL,
	"NAME" varchar(50),
	WIKI varchar(255),
	PRIMARY KEY (ID,GENDER)
);

--
CREATE TABLE FACT_BATTING_STAT (
	SPORT_ID varchar(8) NOT NULL,
	GENDER_ID varchar(8) NOT NULL,
	CATEGORY_ID varchar(20) NOT NULL,
	CLUB_ID varchar(8) NOT NULL,
	COUNTRY_ID varchar(2) NOT NULL,
	SEASON_YEAR numeric NOT NULL,
	PLAYER_ID varchar(16) NOT NULL,
	TEAM_ID numeric NOT NULL,
	AT_BATS numeric,
	RUNS numeric,
	HITS numeric,
	DOUBLES numeric,
	TRIPLES numeric,
	HOME_RUNS numeric,
	RBI numeric,
	TOTAL_BASES numeric,
	BASE_ON_BALLS numeric,
	HIT_BY_PITCHS numeric,
	STRIKE_OUTS numeric,
	GROUND_INTO_DOUBLEPLAYS numeric,
	SACRFICE_FLIES numeric,
	BUNTS numeric,
	STOLEN_BASES numeric,
	CAUGHT_STEALING numeric,
	PRIMARY KEY (SPORT_ID,GENDER_ID,CATEGORY_ID,CLUB_ID,COUNTRY_ID,SEASON_YEAR,PLAYER_ID,TEAM_ID)
);
--
CREATE TABLE FACT_FIELDING_STAT (
	SPORT_ID varchar(8) NOT NULL,
	GENDER_ID varchar(8) NOT NULL,
	CATEGORY_ID varchar(20) NOT NULL,
	CLUB_ID varchar(8) NOT NULL,
	COUNTRY_ID varchar(2) NOT NULL,
	SEASON_YEAR numeric NOT NULL,
	PLAYER_ID varchar(16) NOT NULL,
	TEAM_ID numeric NOT NULL,
	GAMES_PLAYED_AT_POSITION numeric,
	TOTAL_CHANCES numeric,
	TOTAL_SUCCESSFUL_CHANCES numeric,
	PUTOUTS numeric,
	ASSISTS numeric,
	ERRORS numeric,
	DOUBLEPLAYS numeric,
	STOLEN_BASES_AGAINST numeric,
	PLAYERS_CAUGHT_STEELING numeric,
	PASSED_BALLS numeric,
	CATCHER_INTERFERENCES numeric,
	PRIMARY KEY (SPORT_ID,GENDER_ID,CATEGORY_ID,CLUB_ID,COUNTRY_ID,SEASON_YEAR,PLAYER_ID,TEAM_ID)
);

--
CREATE TABLE FACT_PITCHING_STAT (
	SPORT_ID varchar(8) NOT NULL,
	GENDER_ID varchar(8) NOT NULL,
	CATEGORY_ID varchar(20) NOT NULL,
	CLUB_ID varchar(8) NOT NULL,
	COUNTRY_ID varchar(2) NOT NULL,
	SEASON_YEAR numeric NOT NULL,
	PLAYER_ID varchar(16) NOT NULL,
	TEAM_ID numeric NOT NULL,
	WINS numeric,
	LOSSES numeric,
	GAMES numeric,
	GAMES_STARTED numeric,
	SAVES numeric,
	COMPLETE_GAMES numeric,
	SHUTOUTS numeric,
	INNINGS_PITCHED_LABEL numeric(0,1),
	INNINGS_PITCHED_DEC numeric,
	INNING_OUTS_PITCHED numeric,
	HITS numeric,
	RUNS numeric,
	EARNED_RUNS numeric,
	WALKS numeric,
	STRIKE_OUTS numeric,
	DOUBLES numeric,
	TRIPLES numeric,
	HOME_RUNS numeric,
	AT_BATS numeric,
	WILD_PITCHES numeric,
	HIT_BY_PITCHS numeric,
	BALKS numeric,
	SACRIFICE_FLIES_AGAINST numeric,
	BUNTS_AGAINST numeric,
	GROUND_OUTS numeric,
	FLY_OUTS numeric,
	PRIMARY KEY (SPORT_ID,GENDER_ID,CATEGORY_ID,CLUB_ID,COUNTRY_ID,SEASON_YEAR,PLAYER_ID,TEAM_ID)
);
CREATE TABLE LU_TEAM_SPLIT (
	PLAYER_NAME varchar(128) NOT NULL,
	SPORT varchar(26) NOT NULL,
	GENDER varchar(26) NOT NULL,
	CLUB varchar(26) NOT NULL,
	CATEGORY varchar(26) NOT NULL,
	TEAM numeric(38) NOT NULL,
	"YEAR" numeric(38) NOT NULL,
	COUNTRY_ID varchar(26) NOT NULL
);
CREATE TABLE RSLT_PLAYER (
	"KEY" varchar(2000) NOT NULL,
	KEY_SEQ varchar(2000) NOT NULL,
	LAST_NAME varchar(255),
	FIRST_NAME varchar(255)
);
CREATE TABLE STG_BATTING_STAT (
	SPORT_ID varchar(8),
	DIVISION varchar(20),
	GENDER_ID varchar(8),
	SEASON_YEAR numeric,
	LAST_NAME varchar(255),
	FIRST_NAME varchar(255),
	TEAM varchar(3),
	COUNTRY_ID varchar(2),
	AB numeric,
	R numeric,
	H numeric,
	H2 numeric,
	H3 numeric,
	HR numeric,
	RBI numeric,
	TB numeric,
	"AVG" numeric(5,3),
	SLG numeric(5,3),
	OBP numeric(5,3),
	OPS numeric(5,3),
	BB numeric,
	HBP numeric,
	SO numeric,
	GDP numeric,
	SF numeric,
	SH numeric,
	SB numeric,
	CS numeric
);
CREATE TABLE STG_FIELDING_STAT (
	SPORT_ID varchar(8),
	DIVISION varchar(20),
	GENDER_ID varchar(8),
	SEASON_YEAR numeric,
	LAST_NAME varchar(255),
	FIRST_NAME varchar(255),
	TEAM varchar(3),
	COUNTRY_ID varchar(2),
	G numeric,
	C numeric,
	PO numeric,
	A numeric,
	E numeric,
	FLDP numeric(5,3),
	DP numeric,
	SBA numeric,
	CSB numeric,
	SBAP numeric(5,1),
	PB numeric,
	CI numeric
);
CREATE TABLE STG_PITCHING_STAT (
	SPORT_ID varchar(8),
	DIVISION varchar(20),
	GENDER_ID varchar(8),
	SEASON_YEAR numeric,
	LAST_NAME varchar(255),
	FIRST_NAME varchar(255),
	TEAM varchar(3),
	COUNTRY_ID varchar(2),
	W numeric,
	L numeric,
	ERA numeric(5,2),
	APP numeric,
	GS numeric,
	SV numeric,
	CG numeric,
	SHO numeric,
	IP numeric(5,1),
	H numeric,
	R numeric,
	ER numeric,
	BB numeric,
	SO numeric,
	H2 numeric,
	H3 numeric,
	HR numeric,
	AB numeric,
	BAVG numeric(5,3),
	WP numeric,
	HBP numeric,
	BK numeric,
	SFA numeric,
	SHA numeric,
	"GO" numeric,
	FO numeric
);
CREATE TABLE STG_PLAYER (
	UNIFORM_NUMBER numeric,
	PLAYER_NAME varchar(255),
	"POSITION" varchar(50),
	BATS char(1),
	THROWS char(1),
	HT numeric,
	WT numeric,
	YOB numeric,
	TEAM varchar(3)
);
CREATE TABLE TEMP_DIM_CLUB_COUNTRY_BRIDGE (
	CLUB_ID varchar(20),
	COUNTRY_ID varchar(2),
	CREBY varchar(32),
	CRE timestamp,
	LUBY varchar(32),
	LU timestamp
);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AA', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ACA', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AMS', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AND', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ANT', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ANT', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AST', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ATL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BB', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BBC', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BCN', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BER', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BEV', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BIN', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BMB', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BOL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BOR', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BOZ', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRA', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRE', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRG', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRI', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAG', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAM', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAN', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAP', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAS', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CER', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CHI', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('COD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('COL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CRO', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DD', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DEU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DI', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DKI', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DOI', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DRA', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DRI', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ELL', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('EUR', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('EXA', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('FC', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('FEN', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('FIO', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GEN', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GH', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GOD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GRE', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GRO', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HB', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HCA', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HEI', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HOB', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HTF', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('IN', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('INA', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('IRA', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('JEM', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('JRG', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LAN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LBC', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LDC', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LDM', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LEU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LIE', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LIM', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LIN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LLC', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LON', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MAC', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MAR', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MAR', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MER', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MIL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MIR', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MOD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MON', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MON', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MOR', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MS', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MSG', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAM', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAV', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NE2', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NEP', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NET', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OBB', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OGZ', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OLT', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OLY', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OOS', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OUD', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PAD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PAR', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PAU', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PEL', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PIO', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('POP', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('POV', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('QUI', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RCH', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RED', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('REG', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RES', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RFA', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RIM', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RIV', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ROE', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RON', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ROV', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RSM', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SAL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SBO', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SEN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SER', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SET', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SHB', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SPA', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('STA', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('STO', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TBS', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TON', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TOR', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TOR', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TOU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TTT', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TWI', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TZH', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('UVV', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VER', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VET', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VIL', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VM', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VW', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('WBA', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('WIE', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ZON', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ZOT', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO DIM_COMPETITION(COMPETITION_ID, COMPETITION, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'National Competition', 'C##BASEBALL', '2024-06-25 16:29:26', null, null);
INSERT INTO DIM_COMPETITION(COMPETITION_ID, COMPETITION, CREBY, CRE, LUBY, LU) VALUES ('INTL', 'International Competition', 'C##BASEBALL', '2024-06-25 16:29:26', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'AT', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'BE', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'CH', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'CZ', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'DE', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'DK', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'ES', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'FR', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'GB', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'HR', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'IL', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'IT', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'NL', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'PL', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'SE', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO DIM_COMPETITION_COUNTRY_BRIDGE(COMPETITION_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAT', 'UA', 'C##BASEBALL', '2024-06-25 16:34:51', null, null);
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Bariaux Ludovic', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Bombart Bastien', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Cadeddu Matteo', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Clerbois Theo', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Cludts Quentin', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('De Groof Frédérick', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Deletombe Maxime', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Durieux Laurent', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Fahandezh Saadi Mohsen', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Genao Rigoberto', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Goudelouf Sébastien', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Guerra Elizondo César Emilio', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Guerra Guerrero César', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Guy Romain', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('HAMMOUTEN Farid', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Laurent David', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Malpoix Pascal', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Nyst Alexandre', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Oesau Guillaume', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Pérez Miguel', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Piret Christophe', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Raymond Xavier', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Rivera Hegel Luis Diego', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Roberts Joshua', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Schmitz Donatien', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Vandendriessche Nicolas', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Zidoune Karim', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Almagro Gomez Jose Raul', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Cedeño Daudinot Alain', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Cortes Rojas Carlos Alberto', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Fernandez Cuba Adalberto', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Freitez Jhoanderson', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Garcia Pupo Oreste', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Ghys Frédéric', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Lambeau Jean-Marc', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Limonta Padilla Alejandro', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Mumenthaler Frédéric', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Peña Gonzalez Francisco', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Perez Cabarallo Arturo', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Sakai Yosuke', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Tran David', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Urbaez Feliz Joni Antonio', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Urquiaga Rodriguez Carlos Enrique', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, "YEAR", COUNTRY_ID) VALUES ('Veras Luciano Luis Manuel', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AA', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ACA', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AMS', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AND', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ANT', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ANT', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('AST', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ATL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BB', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BBC', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BCN', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BER', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BEV', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BIN', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BMB', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BOL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BOR', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BOZ', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRA', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRE', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRG', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRI', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('BRU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAG', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAM', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAN', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAP', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CAS', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CER', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CHI', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('COD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('COL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('CRO', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DD', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DEU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DI', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DKI', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DOI', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DRA', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('DRI', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ELL', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('EUR', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('EXA', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('FC', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('FEN', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('FIO', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GEN', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GH', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GOD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GRE', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('GRO', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HB', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HCA', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HEI', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HOB', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('HTF', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('IN', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('INA', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('IRA', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('JEM', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('JRG', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LAN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LBC', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LDC', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LDM', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LEU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LIE', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LIM', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LIN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LLC', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('LON', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MAC', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MAR', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MAR', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MER', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MIL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MIR', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MOD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MON', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MON', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MOR', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MS', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('MSG', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAM', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NAV', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NE2', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NEP', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('NET', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OBB', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OGZ', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OLT', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OLY', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OOS', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('OUD', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PAD', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PAR', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PAU', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PEL', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('PIO', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('POP', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('POV', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('QUI', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RCH', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RED', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('REG', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RES', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RFA', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RIM', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RIV', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ROE', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RON', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ROV', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('RSM', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SAL', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SBO', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SEN', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SER', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SET', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SHB', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('SPA', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('STA', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('STO', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TBS', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TON', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TOR', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TOR', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TOU', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TTT', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TWI', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('TZH', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('UVV', 'NL', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VER', 'IT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VET', 'GB', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VIL', 'ES', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VM', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('VW', 'AT', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('WBA', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('WIE', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ZON', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
INSERT INTO TEMP_DIM_CLUB_COUNTRY_BRIDGE(CLUB_ID, COUNTRY_ID, CREBY, CRE, LUBY, LU) VALUES ('ZOT', 'BE', 'C##BASEBALL', '2024-06-15 16:11:38', null, null);
ALTER TABLE DIM_COMPETITION_COUNTRY_BRIDGE
	ADD FOREIGN KEY (COMPETITION_ID)
	REFERENCES DIM_COMPETITION (COMPETITION_ID);


ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (SEASON_YEAR)
	REFERENCES DIM_SEASON (SEASON_YEAR);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (CLUB_ID)
	REFERENCES DIM_CLUB (ID);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (SPORT_ID)
	REFERENCES DIM_SPORT (ID);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (SPORT_ID)
	REFERENCES DIM_CATEGORY (SPORT_ID);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (PLAYER_ID)
	REFERENCES DIM_PLAYER (ID);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (GENDER_ID)
	REFERENCES null (null);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (GENDER_ID)
	REFERENCES null (null);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (COUNTRY_ID)
	REFERENCES null (null);

ALTER TABLE FACT_BATTING_STAT
	ADD FOREIGN KEY (CATEGORY_ID)
	REFERENCES null (null);


ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (CLUB_ID,COUNTRY_ID)
	REFERENCES DIM_CLUB (ID,COUNTRY_ID);

ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (PLAYER_ID)
	REFERENCES DIM_PLAYER (ID);

ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (SEASON_YEAR)
	REFERENCES DIM_SEASON (SEASON_YEAR);

ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (SPORT_ID)
	REFERENCES DIM_SPORT (ID);

ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (SPORT_ID)
	REFERENCES DIM_CATEGORY (SPORT_ID);

ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (GENDER_ID)
	REFERENCES null (null);

ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (GENDER_ID)
	REFERENCES null (null);

ALTER TABLE FACT_FIELDING_STAT
	ADD FOREIGN KEY (CATEGORY_ID)
	REFERENCES null (null);


ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (SEASON_YEAR)
	REFERENCES DIM_SEASON (SEASON_YEAR);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (PLAYER_ID)
	REFERENCES DIM_PLAYER (ID);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (SPORT_ID)
	REFERENCES DIM_SPORT (ID);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (SPORT_ID)
	REFERENCES DIM_CATEGORY (SPORT_ID);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (CLUB_ID)
	REFERENCES DIM_CLUB (ID);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (COUNTRY_ID)
	REFERENCES null (null);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (GENDER_ID)
	REFERENCES null (null);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (GENDER_ID)
	REFERENCES null (null);

ALTER TABLE FACT_PITCHING_STAT
	ADD FOREIGN KEY (CATEGORY_ID)
	REFERENCES null (null);


