--------------------------------------------------------
--  File created - Friday-July-19-2024
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LU_TEAM_SPLIT
--------------------------------------------------------

CREATE TABLE LU_TEAM_SPLIT (
	PLAYER_NAME varchar(128) NOT NULL,
	SPORT varchar(26) NOT NULL,
	GENDER varchar(26) NOT NULL,
	CLUB varchar(26) NOT NULL,
	CATEGORY varchar(26) NOT NULL,
	TEAM numeric(38) NOT NULL,
	season_YEAR numeric(38) NOT NULL,
	COUNTRY_ID varchar(26) NOT NULL
);

INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Bariaux Ludovic', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Bombart Bastien', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Cadeddu Matteo', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Clerbois Theo', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Cludts Quentin', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('De Groof Frédérick', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Deletombe Maxime', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Durieux Laurent', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Fahandezh Saadi Mohsen', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Genao Rigoberto', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Goudelouf Sébastien', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Guerra Elizondo César Emilio', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Guerra Guerrero César', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Guy Romain', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('HAMMOUTEN Farid', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Laurent David', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Malpoix Pascal', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Nyst Alexandre', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Oesau Guillaume', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Pérez Miguel', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Piret Christophe', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Raymond Xavier', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Rivera Hegel Luis Diego', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Roberts Joshua', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Schmitz Donatien', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Vandendriessche Nicolas', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Zidoune Karim', 'BB', 'M', 'BRI', 'D2', 2, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Almagro Gomez Jose Raul', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Cedeño Daudinot Alain', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Cortes Rojas Carlos Alberto', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Fernandez Cuba Adalberto', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Freitez Jhoanderson', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Garcia Pupo Oreste', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Ghys Frédéric', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Lambeau Jean-Marc', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Limonta Padilla Alejandro', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Mumenthaler Frédéric', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Peña Gonzalez Francisco', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Perez Cabarallo Arturo', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Sakai Yosuke', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Tran David', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Urbaez Feliz Joni Antonio', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Urquiaga Rodriguez Carlos Enrique', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
INSERT INTO LU_TEAM_SPLIT(PLAYER_NAME, SPORT, GENDER, CLUB, CATEGORY, TEAM, season_YEAR, COUNTRY_ID) VALUES ('Veras Luciano Luis Manuel', 'BB', 'M', 'BRI', 'D2', 1, 2024, 'BE');
