/*
Copyright (c) 2023, Antonio Alberto Pérez Pérez
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree.
*/

--------------------------------------------------------
--  File created - Monday-December-25-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table DIM_PLAYER
--------------------------------------------------------

  CREATE TABLE "C##BASEBALL"."DIM_PLAYER" 
   (	"ID" VARCHAR2(16 BYTE), 
	"LAST_NAME" VARCHAR2(255 BYTE), 
	"FIRST_NAME" VARCHAR2(255 BYTE), 
	"POSITION" VARCHAR2(16 BYTE), 
	"BATS" VARCHAR2(10 BYTE), 
	"THROWS" VARCHAR2(10 BYTE), 
	"YOB" NUMBER, 
	"UNIFORM_NUMBER" VARCHAR2(3 BYTE), 
	"LICENSE_NUMBER" VARCHAR2(16 BYTE) DEFAULT null, 
	"LICENSE_TYPE" VARCHAR2(8 BYTE) DEFAULT null
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PLAYER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BASEBALL"."PLAYER_PK" ON "C##BASEBALL"."DIM_PLAYER" ("ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table DIM_PLAYER
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."DIM_PLAYER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."DIM_PLAYER" ADD CONSTRAINT "PLAYER_PK" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
