/*
Copyright (c) 2023, Antonio Alberto Pérez Pérez
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree.
*/

--------------------------------------------------------
--  File created - Tuesday-December-26-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACT_FIELDING_STAT
--------------------------------------------------------

  CREATE TABLE "C##BASEBALL"."FACT_FIELDING_STAT" 
   (	"SPORT_ID" VARCHAR2(8 BYTE), 
	"GENDER_ID" VARCHAR2(8 BYTE), 
	"CATEGORY_ID" VARCHAR2(8 BYTE), 
	"CLUB_ID" VARCHAR2(8 BYTE), 
	"SEASON_YEAR" NUMBER(*,0), 
	"PLAYER_ID" VARCHAR2(16 BYTE), 
	"TEAM_ID" NUMBER(*,0), 
	"GAMES_PLAYED_AT_POSITION" NUMBER(*,0), 
	"TOTAL_CHANCES" NUMBER(*,0), 
	"TOTAL_SUCCESSFUL_CHANCES" NUMBER(*,0), 
	"PUTOUTS" NUMBER(*,0), 
	"ASSISTS" NUMBER(*,0), 
	"ERRORS" NUMBER(*,0), 
	"DOUBLEPLAYS" NUMBER(*,0), 
	"STOLEN_BASES_AGAINST" NUMBER(*,0), 
	"PLAYERS_CAUGHT_STEELING" NUMBER(*,0), 
	"PASSED_BALLS" NUMBER(*,0), 
	"CATCHER_INTERFERENCES" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACT_FIELDING_STAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BASEBALL"."FACT_FIELDING_STAT_PK" ON "C##BASEBALL"."FACT_FIELDING_STAT" ("SPORT_ID", "GENDER_ID", "CATEGORY_ID", "CLUB_ID", "SEASON_YEAR", "PLAYER_ID", "TEAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACT_FIELDING_STAT
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" MODIFY ("SPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" MODIFY ("GENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" MODIFY ("CLUB_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" MODIFY ("SEASON_YEAR" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" MODIFY ("PLAYER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" ADD CONSTRAINT "FACT_FIELDING_STAT_PK" PRIMARY KEY ("SPORT_ID", "GENDER_ID", "CATEGORY_ID", "CLUB_ID", "SEASON_YEAR", "PLAYER_ID", "TEAM_ID")
  USING INDEX "C##BASEBALL"."FACT_FIELDING_STAT_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACT_FIELDING_STAT
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" ADD CONSTRAINT "FIELDING_STAT_SPORT_FK" FOREIGN KEY ("SPORT_ID", "GENDER_ID")
	  REFERENCES "C##BASEBALL"."DIM_SPORT" ("ID", "GENDER") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" ADD CONSTRAINT "FIELDING_STAT_CATEGORY_FK" FOREIGN KEY ("SPORT_ID", "GENDER_ID", "CATEGORY_ID")
	  REFERENCES "C##BASEBALL"."DIM_CATEGORY" ("SPORT_ID", "GENDER", "ID") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" ADD CONSTRAINT "FIELDING_STAT_CLUB_FK" FOREIGN KEY ("CLUB_ID")
	  REFERENCES "C##BASEBALL"."DIM_CLUB" ("ID") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" ADD CONSTRAINT "FIELDING_STAT_SEASON_FK" FOREIGN KEY ("SEASON_YEAR")
	  REFERENCES "C##BASEBALL"."DIM_SEASON" ("SEASON_YEAR") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_FIELDING_STAT" ADD CONSTRAINT "FIELDING_STAT_PLAYER_FK" FOREIGN KEY ("PLAYER_ID")
	  REFERENCES "C##BASEBALL"."DIM_PLAYER" ("ID") ENABLE;
