--------------------------------------------------------
--  File created - Monday-December-25-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACT_BATTING_STAT
--------------------------------------------------------

  CREATE TABLE "C##BASEBALL"."FACT_BATTING_STAT" 
   (	"SPORT_ID" VARCHAR2(8 BYTE), 
	"GENDER_ID" VARCHAR2(8 BYTE), 
	"CATEGORY_ID" VARCHAR2(8 BYTE), 
	"CLUB_ID" VARCHAR2(8 BYTE), 
	"SEASON_YEAR" NUMBER(*,0), 
	"PLAYER_ID" VARCHAR2(16 BYTE), 
	"TEAM_ID" NUMBER(*,0), 
	"AT_BATS" NUMBER(*,0), 
	"RUNS" NUMBER(*,0), 
	"HITS" NUMBER(*,0), 
	"DOUBLES" NUMBER(*,0), 
	"TRIPLES" NUMBER(*,0), 
	"HOME_RUNS" NUMBER(*,0), 
	"RBI" NUMBER(*,0), 
	"TOTAL_BASES" NUMBER(*,0), 
	"BASE_ON_BALLS" NUMBER(*,0), 
	"HIT_BY_PITCHS" NUMBER(*,0), 
	"STRIKE_OUTS" NUMBER(*,0), 
	"GROUND_INTO_DOUBLEPLAYS" NUMBER(*,0), 
	"SACRFICE_FLIES" NUMBER(*,0), 
	"BUNTS" NUMBER(*,0), 
	"STOLEN_BASES" NUMBER(*,0), 
	"CAUGHT_STEALING" NUMBER(*,0)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACT_BATTING_STAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BASEBALL"."FACT_BATTING_STAT_PK" ON "C##BASEBALL"."FACT_BATTING_STAT" ("SPORT_ID", "GENDER_ID", "CATEGORY_ID", "CLUB_ID", "SEASON_YEAR", "PLAYER_ID", "TEAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACT_BATTING_STAT
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" MODIFY ("SPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" MODIFY ("GENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" MODIFY ("CLUB_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" MODIFY ("SEASON_YEAR" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" MODIFY ("PLAYER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" ADD CONSTRAINT "FACT_BATTING_STAT_PK" PRIMARY KEY ("SPORT_ID", "GENDER_ID", "CATEGORY_ID", "CLUB_ID", "SEASON_YEAR", "PLAYER_ID", "TEAM_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACT_BATTING_STAT
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" ADD CONSTRAINT "BATTING_STAT_SPORT_FK" FOREIGN KEY ("SPORT_ID", "GENDER_ID")
	  REFERENCES "C##BASEBALL"."DIM_SPORT" ("ID", "GENDER") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" ADD CONSTRAINT "BATTING_STAT_CATEGORY_FK" FOREIGN KEY ("SPORT_ID", "GENDER_ID", "CATEGORY_ID")
	  REFERENCES "C##BASEBALL"."DIM_CATEGORY" ("SPORT_ID", "GENDER", "ID") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" ADD CONSTRAINT "BATTING_STAT_CLUB_FK" FOREIGN KEY ("CLUB_ID")
	  REFERENCES "C##BASEBALL"."DIM_CLUB" ("ID") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" ADD CONSTRAINT "BATTING_STAT_SEASON_FK" FOREIGN KEY ("SEASON_YEAR")
	  REFERENCES "C##BASEBALL"."DIM_SEASON" ("SEASON_YEAR") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_BATTING_STAT" ADD CONSTRAINT "BATTING_STAT_PLAYER_FK" FOREIGN KEY ("PLAYER_ID")
	  REFERENCES "C##BASEBALL"."DIM_PLAYER" ("ID") ENABLE;
