/*
Copyright (c) 2023, Antonio Alberto Pérez Pérez
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree.
*/

--------------------------------------------------------
--  File created - Tuesday-December-26-2023   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table FACT_PITCHING_STAT
--------------------------------------------------------

  CREATE TABLE "C##BASEBALL"."FACT_PITCHING_STAT" 
   (	"SPORT_ID" VARCHAR2(8 BYTE), 
	"GENDER_ID" VARCHAR2(8 BYTE), 
	"CATEGORY_ID" VARCHAR2(8 BYTE), 
	"CLUB_ID" VARCHAR2(8 BYTE), 
	"SEASON_YEAR" NUMBER(*,0), 
	"PLAYER_ID" VARCHAR2(16 BYTE), 
	"TEAM_ID" NUMBER(*,0), 
	"WINS" NUMBER(*,0), 
	"LOSSES" NUMBER(*,0), 
	"GAMES" NUMBER(*,0), 
	"GAMES_STARTED" NUMBER(*,0), 
	"SAVES" NUMBER(*,0), 
	"COMPLETE_GAMES" NUMBER(*,0), 
	"SHUTOUTS" NUMBER(*,0), 
	"INNINGS_PITCHED_LABEL" NUMBER(*,1), 
	"INNINGS_PITCHED_DEC" NUMBER, 
	"INNING_OUTS_PITCHED" NUMBER(*,0), 
	"HITS" NUMBER(*,0), 
	"RUNS" NUMBER(*,0), 
	"EARNED_RUNS" NUMBER(*,0), 
	"WALKS" NUMBER(*,0), 
	"STRIKE_OUTS" NUMBER(*,0), 
	"DOUBLES" NUMBER(*,0), 
	"TRIPLES" NUMBER(*,0), 
	"HOME_RUNS" NUMBER(*,0), 
	"AT_BATS" NUMBER(*,0), 
	"WILD_PITCHES" NUMBER(*,0), 
	"HIT_BY_PITCHS" NUMBER(*,0), 
	"BALKS" NUMBER(*,0), 
	"SACRIFICE_FLIES_AGAINST" NUMBER(*,0), 
	"BUNTS_AGAINST" NUMBER(*,0), 
	"GROUND_OUTS" NUMBER(*,0), 
	"FLY_OUTS" NUMBER(*,0)
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index FACT_PITCHING_STAT_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "C##BASEBALL"."FACT_PITCHING_STAT_PK" ON "C##BASEBALL"."FACT_PITCHING_STAT" ("SPORT_ID", "GENDER_ID", "CATEGORY_ID", "CLUB_ID", "SEASON_YEAR", "PLAYER_ID", "TEAM_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table FACT_PITCHING_STAT
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" MODIFY ("SPORT_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" MODIFY ("GENDER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" MODIFY ("CATEGORY_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" MODIFY ("CLUB_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" MODIFY ("SEASON_YEAR" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" MODIFY ("PLAYER_ID" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" ADD CONSTRAINT "FACT_PITCHING_STAT_PK" PRIMARY KEY ("SPORT_ID", "GENDER_ID", "CATEGORY_ID", "CLUB_ID", "SEASON_YEAR", "PLAYER_ID", "TEAM_ID")
  USING INDEX "C##BASEBALL"."FACT_PITCHING_STAT_PK"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table FACT_PITCHING_STAT
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" ADD CONSTRAINT "PITCHING_STAT_SPORT_FK" FOREIGN KEY ("SPORT_ID", "GENDER_ID")
	  REFERENCES "C##BASEBALL"."DIM_SPORT" ("ID", "GENDER") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" ADD CONSTRAINT "PITCHING_STAT_CATEGORY_FK" FOREIGN KEY ("SPORT_ID", "GENDER_ID", "CATEGORY_ID")
	  REFERENCES "C##BASEBALL"."DIM_CATEGORY" ("SPORT_ID", "GENDER", "ID") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" ADD CONSTRAINT "PITCHING_STAT_CLUB_FK" FOREIGN KEY ("CLUB_ID")
	  REFERENCES "C##BASEBALL"."DIM_CLUB" ("ID") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" ADD CONSTRAINT "PITCHING_STAT_SEASON_FK" FOREIGN KEY ("SEASON_YEAR")
	  REFERENCES "C##BASEBALL"."DIM_SEASON" ("SEASON_YEAR") ENABLE;
  ALTER TABLE "C##BASEBALL"."FACT_PITCHING_STAT" ADD CONSTRAINT "PITCHING_STAT_PLAYER_FK" FOREIGN KEY ("PLAYER_ID")
	  REFERENCES "C##BASEBALL"."DIM_PLAYER" ("ID") ENABLE;
