--------------------------------------------------------
--  File created - Friday-May-03-2024
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Table LU_TEAM_SPLIT
--------------------------------------------------------

  CREATE TABLE "C##BASEBALL"."LU_TEAM_SPLIT"
   (	"PLAYER_NAME" VARCHAR2(128 BYTE),
	"SPORT" VARCHAR2(26 BYTE),
	"GENDER" VARCHAR2(26 BYTE),
	"CLUB" VARCHAR2(26 BYTE),
	"CATEGORY" VARCHAR2(26 BYTE),
	"TEAM" NUMBER(38,0),
	"YEAR" NUMBER(38,0),
	"COUNTRY_ID" VARCHAR2(26 BYTE)
   ) SEGMENT CREATION IMMEDIATE
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--SET DEFINE OFF;
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Bariaux Ludovic','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Bombart Bastien','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Cadeddu Matteo','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Clerbois Theo','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Cludts Quentin','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('De Groof Frédérick','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Deletombe Maxime','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Durieux Laurent','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Fahandezh Saadi Mohsen','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Genao Rigoberto','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Goudelouf Sébastien','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Guerra Elizondo César Emilio','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Guerra Guerrero César','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Guy Romain','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('HAMMOUTEN Farid','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Laurent David','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Malpoix Pascal','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Nyst Alexandre','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Oesau Guillaume','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Pérez Miguel','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Piret Christophe','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Raymond Xavier','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Rivera Hegel Luis Diego','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Roberts Joshua','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Schmitz Donatien','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Vandendriessche Nicolas','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Zidoune Karim','BB','M','BRI','D2',2,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Almagro Gomez Jose Raul','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Cedeño Daudinot Alain','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Cortes Rojas Carlos Alberto','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Fernandez Cuba Adalberto','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Freitez Jhoanderson','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Garcia Pupo Oreste','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Ghys Frédéric','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Lambeau Jean-Marc','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Limonta Padilla Alejandro','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Mumenthaler Frédéric','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Peña Gonzalez Francisco','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Perez Cabarallo Arturo','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Sakai Yosuke','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Tran David','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Urbaez Feliz Joni Antonio','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Urquiaga Rodriguez Carlos Enrique','BB','M','BRI','D2',1,2024,'BE');
Insert into C##BASEBALL.LU_TEAM_SPLIT (PLAYER_NAME,SPORT,GENDER,CLUB,CATEGORY,TEAM,YEAR,COUNTRY_ID) values ('Veras Luciano Luis Manuel','BB','M','BRI','D2',1,2024,'BE');

commit
;
--------------------------------------------------------
--  Constraints for Table LU_TEAM_SPLIT
--------------------------------------------------------

  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("PLAYER_NAME" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("SPORT" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("GENDER" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("CLUB" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("CATEGORY" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("TEAM" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("YEAR" NOT NULL ENABLE);
  ALTER TABLE "C##BASEBALL"."LU_TEAM_SPLIT" MODIFY ("COUNTRY_ID" NOT NULL ENABLE);
